services:
  - type: web
    name: unitool-proxy
    runtime: node
    plan: free
    rootDir: app
    buildCommand: npm install && npm run build
    startCommand: node out/index.js
    autoDeploy: true
